// <auto-generated />
using System;
using Ideku.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ideku.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251030042957_InitialMigrate")]
    partial class InitialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ideku.Models.Entities.Approver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApproverName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ApproverName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Approvers_IsActive");

                    b.ToTable("Approvers");
                });

            modelBuilder.Entity("Ideku.Models.Entities.ApproverRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("ApproverId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("IX_ApproverRoles_ApproverId");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("IX_ApproverRoles_RoleId");

                    b.ToTable("ApproverRoles");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CategoryName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Desc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Desc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Department", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("DivisiId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("DivisiId")
                        .IsFixedLength();

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("NameDepartment")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NameDepartment");

                    b.HasKey("Id");

                    b.HasIndex("DivisiId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Division", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("Id")
                        .IsFixedLength();

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("NameDivision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NameDivision");

                    b.HasKey("Id");

                    b.ToTable("Divisions");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Employee", b =>
                {
                    b.Property<string>("EMP_ID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("EMP_ID");

                    b.Property<string>("DEPARTEMENT")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(3)")
                        .HasColumnName("DEPARTEMENT");

                    b.Property<string>("DIVISION")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("char(3)")
                        .HasColumnName("DIVISION");

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("EMP_STATUS")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("EMP_STATUS");

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("NAME");

                    b.Property<string>("POSITION_LVL")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("POSITION_LVL");

                    b.Property<string>("POSITION_TITLE")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("POSITION_TITLE");

                    b.HasKey("EMP_ID");

                    b.HasIndex("DEPARTEMENT");

                    b.HasIndex("DIVISION");

                    b.ToTable("EMPLIST");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Desc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Desc");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("EventName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Idea", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AttachmentFiles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AttachmentFiles");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryId");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CompletedDate");

                    b.Property<int>("CurrentStage")
                        .HasColumnType("int")
                        .HasColumnName("CurrentStage");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CurrentStatus");

                    b.Property<int?>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("EventId");

                    b.Property<string>("IdeaCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("IdeaCode");

                    b.Property<string>("IdeaIssueBackground")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("IdeaIssueBackground");

                    b.Property<string>("IdeaName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("IdeaName");

                    b.Property<string>("IdeaSolution")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("IdeaSolution");

                    b.Property<long>("InitiatorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("InitiatorUserId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsMilestoneCreated")
                        .HasColumnType("bit")
                        .HasColumnName("IsMilestoneCreated");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit")
                        .HasColumnName("IsRejected");

                    b.Property<int>("MaxStage")
                        .HasColumnType("int")
                        .HasColumnName("MaxStage");

                    b.Property<string>("RejectedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("RejectedReason");

                    b.Property<string>("RelatedDivisionsJson")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RelatedDivisions");

                    b.Property<long>("SavingCost")
                        .HasColumnType("bigint")
                        .HasColumnName("SavingCost");

                    b.Property<long?>("SavingCostValidated")
                        .HasColumnType("bigint")
                        .HasColumnName("SavingCostValidated");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("SubmittedDate");

                    b.Property<string>("ToDepartmentId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("ToDepartmentId");

                    b.Property<string>("ToDivisionId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("ToDivisionId");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedDate");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EventId");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Ideas_IsDeleted");

                    b.HasIndex("ToDepartmentId");

                    b.HasIndex("ToDivisionId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_Ideas_WorkflowId");

                    b.HasIndex("IsDeleted", "CurrentStatus")
                        .HasDatabaseName("IX_Ideas_IsDeleted_CurrentStatus");

                    b.ToTable("Ideas");
                });

            modelBuilder.Entity("Ideku.Models.Entities.IdeaImplementator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("IdeaId")
                        .HasColumnType("bigint")
                        .HasColumnName("IdeaId");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .HasDatabaseName("IX_IdeaImplementators_IdeaId");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_IdeaImplementators_Role");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_IdeaImplementators_UserId");

                    b.HasIndex("IdeaId", "Role")
                        .HasDatabaseName("IX_IdeaImplementators_IdeaId_Role");

                    b.HasIndex("IdeaId", "UserId")
                        .HasDatabaseName("IX_IdeaImplementators_IdeaId_UserId");

                    b.ToTable("IdeaImplementators");
                });

            modelBuilder.Entity("Ideku.Models.Entities.IdeaMonitoring", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CostSaveActual")
                        .HasColumnType("bigint")
                        .HasColumnName("CostSaveActual");

                    b.Property<long?>("CostSaveActualValidated")
                        .HasColumnType("bigint")
                        .HasColumnName("CostSaveActualValidated");

                    b.Property<long?>("CostSavePlan")
                        .HasColumnType("bigint")
                        .HasColumnName("CostSavePlan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("IdeaId")
                        .HasColumnType("bigint")
                        .HasColumnName("IdeaId");

                    b.Property<string>("MonitoringName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("MonitoringName");

                    b.Property<DateTime>("MonthFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("MonthFrom");

                    b.Property<DateTime>("MonthTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("MonthTo");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId")
                        .HasDatabaseName("IX_IdeaMonitorings_IdeaId");

                    b.HasIndex("MonthFrom")
                        .HasDatabaseName("IX_IdeaMonitorings_MonthFrom");

                    b.HasIndex("MonthTo")
                        .HasDatabaseName("IX_IdeaMonitorings_MonthTo");

                    b.HasIndex("IdeaId", "MonthFrom", "MonthTo")
                        .HasDatabaseName("IX_IdeaMonitorings_IdeaId_Period");

                    b.ToTable("IdeaMonitorings");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Milestone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatorEmployeeId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("CreatorEmployeeId");

                    b.Property<string>("CreatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CreatorName");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndDate");

                    b.Property<long>("IdeaId")
                        .HasColumnType("bigint")
                        .HasColumnName("IdeaId");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Note");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartDate");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Status");

                    b.Property<string>("TitleMilestone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TitleMilestone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Ideku.Models.Entities.MilestonePIC", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<long>("MilestoneId")
                        .HasColumnType("bigint")
                        .HasColumnName("MilestoneId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId")
                        .HasDatabaseName("IX_MilestonePICs_MilestoneId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_MilestonePICs_UserId");

                    b.HasIndex("MilestoneId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MilestonePICs_MilestoneId_UserId");

                    b.ToTable("MilestonePICs");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Desc");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RoleName");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Ideku.Models.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActingDepartmentId")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("ActingDepartmentId");

                    b.Property<string>("ActingDivisionId")
                        .HasMaxLength(3)
                        .HasColumnType("char(3)")
                        .HasColumnName("ActingDivisionId");

                    b.Property<DateTime?>("ActingEndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActingEndDate");

                    b.Property<DateTime?>("ActingStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ActingStartDate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CurrentRoleId")
                        .HasColumnType("int")
                        .HasColumnName("CurrentRoleId");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("EmployeeId");

                    b.Property<bool>("IsActing")
                        .HasColumnType("bit")
                        .HasColumnName("IsActing");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleId");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Username");

                    b.HasKey("Id");

                    b.HasIndex("ActingDepartmentId");

                    b.HasIndex("ActingDivisionId");

                    b.HasIndex("CurrentRoleId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Desc")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Desc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("Priority");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("WorkflowName");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Workflows_IsActive");

                    b.HasIndex("IsActive", "Priority")
                        .HasDatabaseName("IX_Workflows_IsActive_Priority");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("Ideku.Models.Entities.WorkflowCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ConditionType");

                    b.Property<string>("ConditionValue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ConditionValue");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Operator");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_WorkflowConditions_WorkflowId");

                    b.HasIndex("ConditionType", "IsActive")
                        .HasDatabaseName("IX_WorkflowConditions_ConditionType_IsActive");

                    b.ToTable("WorkflowConditions");
                });

            modelBuilder.Entity("Ideku.Models.Entities.WorkflowHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Action");

                    b.Property<long>("ActorUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("ActorUserId");

                    b.Property<string>("Comments")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comments");

                    b.Property<int>("FromStage")
                        .HasColumnType("int")
                        .HasColumnName("FromStage");

                    b.Property<long>("IdeaId")
                        .HasColumnType("bigint")
                        .HasColumnName("IdeaId");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("Timestamp");

                    b.Property<int?>("ToStage")
                        .HasColumnType("int")
                        .HasColumnName("ToStage");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("IdeaId");

                    b.ToTable("WorkflowHistory");
                });

            modelBuilder.Entity("Ideku.Models.Entities.WorkflowStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproverId")
                        .HasColumnType("int")
                        .HasColumnName("ApproverId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit")
                        .HasColumnName("IsMandatory");

                    b.Property<bool>("IsParallel")
                        .HasColumnType("bit")
                        .HasColumnName("IsParallel");

                    b.Property<int>("Stage")
                        .HasColumnType("int")
                        .HasColumnName("Stage");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("WorkflowId");

                    b.HasKey("Id");

                    b.HasIndex("ApproverId")
                        .HasDatabaseName("IX_WorkflowStages_ApproverId");

                    b.HasIndex("WorkflowId")
                        .HasDatabaseName("IX_WorkflowStages_WorkflowId");

                    b.HasIndex("WorkflowId", "Stage")
                        .IsUnique()
                        .HasDatabaseName("IX_WorkflowStages_WorkflowId_Stage");

                    b.ToTable("WorkflowStages");
                });

            modelBuilder.Entity("Ideku.Models.Entities.ApproverRole", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Approver", "Approver")
                        .WithMany("ApproverRoles")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Department", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Division", "Division")
                        .WithMany("Departments")
                        .HasForeignKey("DivisiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Employee", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Department", "DepartmentNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("DEPARTEMENT")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Division", "DivisionNavigation")
                        .WithMany("Employees")
                        .HasForeignKey("DIVISION")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentNavigation");

                    b.Navigation("DivisionNavigation");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Idea", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Category", "Category")
                        .WithMany("Ideas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Event", "Event")
                        .WithMany("Ideas")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Ideku.Models.Entities.User", "InitiatorUser")
                        .WithMany("InitiatedIdeas")
                        .HasForeignKey("InitiatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Department", "TargetDepartment")
                        .WithMany("TargetIdeas")
                        .HasForeignKey("ToDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Division", "TargetDivision")
                        .WithMany("TargetIdeas")
                        .HasForeignKey("ToDivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Event");

                    b.Navigation("InitiatorUser");

                    b.Navigation("TargetDepartment");

                    b.Navigation("TargetDivision");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Ideku.Models.Entities.IdeaImplementator", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Idea", "Idea")
                        .WithMany("IdeaImplementators")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.User", "User")
                        .WithMany("ImplementatorAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ideku.Models.Entities.IdeaMonitoring", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Idea", "Idea")
                        .WithMany("IdeaMonitorings")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Milestone", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Idea", "Idea")
                        .WithMany("Milestones")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("Ideku.Models.Entities.MilestonePIC", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Milestone", "Milestone")
                        .WithMany("MilestonePICs")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.User", "User")
                        .WithMany("MilestonePICAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Milestone");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Ideku.Models.Entities.User", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Department", "ActingDepartment")
                        .WithMany()
                        .HasForeignKey("ActingDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ideku.Models.Entities.Division", "ActingDivision")
                        .WithMany()
                        .HasForeignKey("ActingDivisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ideku.Models.Entities.Role", "CurrentRole")
                        .WithMany()
                        .HasForeignKey("CurrentRoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ideku.Models.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("Ideku.Models.Entities.User", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActingDepartment");

                    b.Navigation("ActingDivision");

                    b.Navigation("CurrentRole");

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Ideku.Models.Entities.WorkflowCondition", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Workflow", "Workflow")
                        .WithMany("WorkflowConditions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Ideku.Models.Entities.WorkflowHistory", b =>
                {
                    b.HasOne("Ideku.Models.Entities.User", "ActorUser")
                        .WithMany("WorkflowActions")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Idea", "Idea")
                        .WithMany("WorkflowHistories")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActorUser");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("Ideku.Models.Entities.WorkflowStage", b =>
                {
                    b.HasOne("Ideku.Models.Entities.Approver", "Approver")
                        .WithMany("WorkflowStages")
                        .HasForeignKey("ApproverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ideku.Models.Entities.Workflow", "Workflow")
                        .WithMany("WorkflowStages")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Approver", b =>
                {
                    b.Navigation("ApproverRoles");

                    b.Navigation("WorkflowStages");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Category", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("TargetIdeas");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Division", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");

                    b.Navigation("TargetIdeas");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Employee", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Event", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Idea", b =>
                {
                    b.Navigation("IdeaImplementators");

                    b.Navigation("IdeaMonitorings");

                    b.Navigation("Milestones");

                    b.Navigation("WorkflowHistories");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Milestone", b =>
                {
                    b.Navigation("MilestonePICs");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Ideku.Models.Entities.User", b =>
                {
                    b.Navigation("ImplementatorAssignments");

                    b.Navigation("InitiatedIdeas");

                    b.Navigation("MilestonePICAssignments");

                    b.Navigation("WorkflowActions");
                });

            modelBuilder.Entity("Ideku.Models.Entities.Workflow", b =>
                {
                    b.Navigation("WorkflowConditions");

                    b.Navigation("WorkflowStages");
                });
#pragma warning restore 612, 618
        }
    }
}
